#if !defined(AFX_SRCDBPG_H__A8D43ABF_15FA_4E29_997F_35C483C2DB71__INCLUDED_)
#define AFX_SRCDBPG_H__A8D43ABF_15FA_4E29_997F_35C483C2DB71__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSRCDBPG wrapper class

class CSRCDBPG : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSRCDBPG)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x5ee2fcd7, 0xf527, 0x4900, { 0xaf, 0x7c, 0x33, 0xbc, 0xc6, 0x6, 0x27, 0xfb } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	BOOL GetGotoFirstEnabled();
	void SetGotoFirstEnabled(BOOL);
	BOOL GetGotoLastEnabled();
	void SetGotoLastEnabled(BOOL);
	BOOL GetGotoPrevEnabled();
	void SetGotoPrevEnabled(BOOL);
	BOOL GetGotoNextEnabled();
	void SetGotoNextEnabled(BOOL);
	BOOL GetGotoNewEnabled();
	void SetGotoNewEnabled(BOOL);
	short GetCaptionWidth();
	void SetCaptionWidth(short);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SRCDBPG_H__A8D43ABF_15FA_4E29_997F_35C483C2DB71__INCLUDED_)
